#### Aim of this script: code to make Figure 4 in the main text, as well as code for testing correlation of overall log2FC values between the two tissues ###

library(VennDiagram)
library(grid)

### Gill transplant origin DM CpG overlaps
gill_origin      <- 121   # area 1
gill_transplant  <- 211   # area 2
gill_ori_trans   <- 56    # intersection (area1 ∩ area2)

png("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/gill_venn.png",
    width = 8, height = 8, units = "in", res = 300)

grid.newpage()
venn.plot <- draw.pairwise.venn(
  area1      = gill_origin,
  area2      = gill_transplant,
  cross.area = gill_ori_trans,          # intersection for pairwise
  category   = c("Origin", "Transplant"),
  fill       = c("#e68d4e"), # length 2 for two sets
  alpha      = c(0.4, 0.4),
  lwd        = 0,
  cex        = 0,                     # counts size
  cat.cex    = 0,                       # hide labels (as in your code)
  cat.col    = "black",
  cat.dist   = c(0.05, 0.05)            # length 2 for two sets
)

grid.draw(venn.plot)
dev.off()


### Foot transplant origin DM CpG overlaps

foot_origin      <- 93   # area 1
foot_transplant  <- 124   # area 2
foot_ori_trans   <- 24    # intersection (area1 ∩ area2)

png("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/foot_venn.png",
    width = 8, height = 8, units = "in", res = 300)

grid.newpage()
venn.plot <- draw.pairwise.venn(
  area1      = foot_origin,
  area2      = foot_transplant,
  cross.area = foot_ori_trans,          # intersection for pairwise
  category   = c("Origin", "Transplant"),
  fill       = c("#3bbdcc"), # length 2 for two sets
  alpha      = c(0.4, 0.4),
  lwd        = 0,
  cex        = 0,                     # counts size
  cat.cex    = 0,                       # hide labels (as in your code)
  cat.col    = "black",
  cat.dist   = c(0.05, 0.05)            # length 2 for two sets
)

grid.draw(venn.plot)
dev.off()


### intersection between gill and foot transplant

intersect(unique(merged_all_DM_foot$combined), unique(merged_all_DM_gill$combined))

library(VennDiagram)
library(grid)
library(VennDiagram)
library(grid)

foot_only <- 124
gill_only <- 211
shared    <- 0   # set to the true overlap if > 0

png("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/gill_foot_venn.png",
    width = 8, height = 8, units = "in", res = 300)

grid.newpage()
venn.plot <- draw.pairwise.venn(
  area1 = foot_only,               
  area2 = gill_only,                
  cross.area = shared,
  category = c("Foot", "Gill"),     
  fill = c("#3bbdcc","#e68d4e"),   
  alpha = 0.5,
  lwd = 0,
  cat.cex = 0,
  cex = 0,
  cat.col = "black",
  rotation.degree = 180,
  scaled = TRUE,
  cat.dist = c(0.025, 0.025)
)

dev.off()


#### Pearson's correlation between all logFC in foot and gills ####

#load data
gill_all_logfc<-read_csv("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/gill_unique_all_CpG.csv")
foot_all_logfc<-read_csv("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/foot_unique_all_CpG.csv")

transplant_logfc_gill<-gill_all_logfc %>% 
  filter(Treat=="Transplant")
origin_logfc_gill<-gill_all_logfc %>% 
  filter(Treat=="Origin")

transplant_logfc_foot<-foot_all_logfc %>% 
  filter(Treat=="Transplant")
origin_logfc_foot<-foot_all_logfc %>% 
  filter(Treat=="Origin")


### Pivot both tissues wide by Treat
foot_wide <- foot_all_logfc %>%
  dplyr::select(sample, Treat, logFC) %>%
  pivot_wider(names_from = Treat, values_from = logFC, names_prefix = "Foot_")

gill_wide <- gill_all_logfc %>%
  dplyr::select(sample, Treat, logFC) %>%
  pivot_wider(names_from = Treat, values_from = logFC, names_prefix = "Gill_")

### Join on sample (gene ID)
merged <- inner_join(foot_wide, gill_wide, by = "sample")


### Scatterplot: Foot vs Gill for Transplant
transplant_cor <-
  ggplot(merged, aes(x = Gill_Transplant, y = Foot_Transplant)) +
  geom_point(alpha = 0.5, color = "black", size =1.3, stroke = 0) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    col="red",
    fill = "grey",
    size =1,
    alpha =1) + theme_few() +
  labs(x = "Gills log2FC ",
       y = "Foot log2FC ") +
  theme_few(base_size = 15 )+
  ggpubr::stat_cor(method = "pearson",
                   label.x.npc = "left",  # place at top-left; use "right" for top-right
                   label.y.npc = "top",
                   size = 4)


transplant_cor

# ggsave("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/transplant_cor_foot_gill.png",transplant_cor, height = 4, width=5)

# Scatterplot: Foot vs Gill for Origin
origin_cor<-ggplot(merged, aes(x = Gill_Origin, y = Foot_Origin)) +
  geom_point(alpha = 0.5, color = "black", size =1.3, stroke = 0) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    col="red",
    fill = "grey",
    size =1,
    alpha =1) +
  labs(x = "Gills log2FC ",
       y = "Foot log2FC ") +
  theme_few(base_size = 20 )+
  ggpubr::stat_cor(method = "pearson",
                   label.x.npc = "left",  # place at top-left; use "right" for top-right
                   label.y.npc = "top",
                   size = 8)


origin_cor
# ggsave("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/manuscript/origin_cor_foot_gill.png",origin_cor, height =8, width=12)




### Test if there's any correlation in all log2FC of CpGs between tissues ###
cor_test <- cor.test(merged$Foot_Origin, merged$Gill_Origin, method = "pearson")
cor_test

cor_test <- cor.test(merged$Foot_Transplant, merged$Gill_Transplant, method = "pearson")
cor_test