---
title: "Mann Whitney U test - GO analysis"
author: "Tina Cai"
date: "2025-08-25"
output: html_document
---
```{r}

setwd("/Users/qcai/mytilus_github/Outputs/lfg_files")
go_annot <- read.csv("all_go_terms.csv")

# Compress GO datasheet
go_df <- data.frame(gene_id = go_annot$gene_id,
                    GO_id = go_annot$GO_ID)

go_df <- go_df %>%
  group_by(gene_id) %>%
  summarise(GO = paste(unique(GO_id), collapse = ";"), .groups = "drop")


# # Save the new GO df to the GOMWU directory
# write.table(go_df, "/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/MethylMussel_GO/GO_MWU/GO_df.tab", 
#             row.names=FALSE,sep="\t", 
#             quote = FALSE,
#             col.names = FALSE)


```


```{r}

# GO enrichments using Mann Whitney U tests
setwd("/Users/qcai/mytilus_github/Outputs/lfg_files")
#folder contains all the necessary files for this analysis
# setwd("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/MethylMussel_GO/GO_MWU/")

#Now we multiply them together into a new column

## Ok we also want to bring in our annotations
#I would suggest putting a GO_MWU folder into your working directory for these steps. There is some stuff to download such as the obo files 
#See https://github.com/z0on/GO_MWU

# GO_MWU uses continuous measure of significance (such as fold-change or -log(p-value) ) to identify GO categories that are significantly enriches with either up- or down-regulated genes. The advantage - no need to impose arbitrary significance cutoff.
# If the measure is binary (0 or 1) the script will perform a typical "GO enrichment" analysis based Fisher's exact test: it will show GO categories over-represented among the genes that have 1 as their measure. 
# On the plot, different fonts are used to indicate significance and color indicates enrichment with either up (red) or down (blue) regulated genes. No colors are shown for binary measure analysis.
# The tree on the plot is hierarchical clustering of GO categories based on shared genes. Categories with no branch length between them are subsets of each other.
# The fraction next to GO category name indicates the fracton of "good" genes in it; "good" genes being the ones exceeding the arbitrary absValue cutoff (option in gomwuPlot). For Fisher's based test, specify absValue=0.5. This value does not affect statistics and is used for plotting only.
# Stretch the plot manually to match tree to text

# Mikhail V. Matz, UT Austin, February 2015; matz@utexas.edu

################################################################
# First, press command-D on mac or ctrl-shift-H in Rstudio and navigate to the directory containing scripts and input files. Then edit, mark and execute the following bits of code, one after another.

# Edit these to match your data file names: 
input="average_lfg_gill_transplant_filtered_no_interaction.csv" # two columns of comma-separated values: gene id, continuous measure of significance. To perform standard GO enrichment analysis based on Fisher's exact test, use binary measure (0 or 1, i.e., either sgnificant or not).

#files used: average_lfg_gill_transplant_filtered_no_interaction.csv
#average_lfg_foot_origin_filtered_no_interaction.csv, 
#average_lfg_gill_origin_filtered_no_interaction.csv
#average_lfg_gill_transplant_filtered_no_interaction.csv

goAnnotations="GO_gill_df.tab" # two-column, tab-delimited, one line per gene, multiple GO terms separated by semicolon. If you have multiple lines per gene, use nrify_GOtable.pl prior to running this script.

#for foot: GO_foot_df.tab

goDatabase="go.obo" # download from http://www.geneontology.org/GO.downloads.ontology.shtml
goDivision="CC" # either MF, or BP, or CC
source("/Users/qcai/Documents/UCSC/Kelley_Lab/mytilus/MethylMussel_GO/GO_MWU/gomwu.functions.R")

nrow(input)  # Check number of rows
length(rownames(input)) 

# Calculating stats. It might take ~3 min for MF and BP. Do not rerun it if you just want to replot the data with different cutoffs, go straight to gomwuPlot. If you change any of the numeric values below, delete the files that were generated in previos runs first.
gomwuStats(input, goDatabase, goAnnotations, goDivision,
	perlPath="/usr/bin/perl", # replace with full path to perl executable if it is not in your system's PATH already
	largest=0.01, # a GO category will not be considered if it contains more than this fraction of the total number of genes
	smallest=2,   # a GO category should contain at least this many genes to be considered
	clusterCutHeight=0.25) # threshold for merging similar (gene-sharing) terms. See README for details.
	#Alternative="g") # # threshold for merging similar (gene-sharing) terms. See README for details.
           #	Alternative="g" # by default the MWU test is two-tailed; specify "g" or "l" of you want to test for "greater" or "less" instead. 
           #	Module=TRUE,Alternative="g" # un-remark this if you are analyzing a SIGNED WGCNA module (values: 0 for not in module genes, kME for in-module genes). In the call to gomwuPlot below, specify absValue=0.001 (count number of "good genes" that fall into the module)
           #	Module=TRUE # un-remark this if you are analyzing an UNSIGNED WGCNA module
# do not continue if the printout shows that no GO terms pass 10% FDR.

quartz(quartz.options(width = 5, height = 4))

results=gomwuPlot(input, goAnnotations, goDivision,
#	absValue=-log(0.05,10),  # genes with the measure value exceeding this will be counted as "good genes". Specify absValue=0.001 if you are doing Fisher's exact test for standard GO enrichment or analyzing a WGCNA module (all non-zero genes = "good genes").
	absValue=.001,
	level1=1, # FDR threshold for plotting. Specify level1=1 to plot all GO categories containing genes exceeding the absValue.
	level2=0.05, # FDR cutoff to print in regular (not italic) font.
	level3=0.01, # FDR cutoff to print in large bold font.
	txtsize=1,    # decrease to fit more on one page, or increase (after rescaling the plot so the tree fits the text) for better "word cloud" effect
	treeHeight=1,# height of the hierarchical clustering tree
  colors=c("salmon1","royalblue","lightcoral","skyblue") # these are default colors, un-remar and change if needed
)

# manually rescale the plot so the tree matches the text 
# if there are too many categories displayed, try make it more stringent with level1=0.05,level2=0.01,level3=0.001.  
  

```


```{r}

# Expand the GO terms into a long format for processing, all the average_lfg_'tissue'_'site'_filtered come from running final_foot_DM_analysis.rmd and final_gill_DM_analysis.rmd

go_long <- go_foot_df %>%
  tidyr::separate_rows(GO, sep = ";")

# Join the logFC data with the GO terms
foot_trans_logFC_test <- average_lfg_foot_transplant_filtered %>%
  inner_join(go_long, by = "gene_id")

# Get a list of unique GO terms
unique_go <- unique(foot_trans_logFC_test$GO)


# Perform Mann-Whitney U tests for each GO term
mw_foot_trans <- lapply(unique_go, function(go) {
  # Create a binary grouping factor: TRUE if gene is associated with the current GO
  test_data <- foot_trans_logFC_test %>%
    mutate(is_in_go = GO == go)
  
  # Perform the Mann-Whitney U test
  p_value <- wilcox.test(mean ~ is_in_go, data = test_data)$p.value
  
  # Return the GO term and p-value
  data.frame(GO = go, p_value = p_value)
}) %>%
  bind_rows()

# Apply FDR correction
mw_foot_trans <- mw_foot_trans %>%
  mutate(FDR = p.adjust(p_value, method = "fdr"))

# No sig GO terms after FDR correction
filter(mw_foot_trans, FDR < 0.05)

```

```{r}

#foot origin effect

# Join the logFC data with the GO terms
foot_origin_logFC_test <- average_lfg_foot_origin_filtered %>%
  inner_join(go_long, by = "gene_id")

# Get a list of unique GO terms
unique_go <- unique(foot_origin_logFC_test$GO)


# Perform Mann-Whitney U tests for each GO term
mw_foot_origin <- lapply(unique_go, function(go) {
  # Create a binary grouping factor: TRUE if gene is associated with the current GO
  test_data <- foot_origin_logFC_test %>%
    mutate(is_in_go = GO == go)
  
  # Perform the Mann-Whitney U test
  p_value <- wilcox.test(mean ~ is_in_go, data = test_data)$p.value
  
  # Return the GO term and p-value
  data.frame(GO = go, p_value = p_value)
}) %>%
  bind_rows()

# Apply FDR correction
mw_foot_origin <- mw_foot_origin %>%
  mutate(FDR = p.adjust(p_value, method = "fdr"))

# No sig GO terms after FDR correction
filter(mw_foot_origin, FDR < 0.05)

```

```{r}

#gill origin effect

# Expand the GO terms into a long format for processing
go_long <- go_gill_df %>%
  tidyr::separate_rows(GO, sep = ";")


# Join the logFC data with the GO terms
gill_origin_logFC_test <- average_lfg_gill_origin_filtered %>%
  inner_join(go_long, by = "gene_id")

# Get a list of unique GO terms
unique_go <- unique(gill_origin_logFC_test$GO)


# Perform Mann-Whitney U tests for each GO term
mw_gill_origin <- lapply(unique_go, function(go) {
  # Create a binary grouping factor: TRUE if gene is associated with the current GO
  test_data <- gill_origin_logFC_test %>%
    mutate(is_in_go = GO == go)
  
  # Perform the Mann-Whitney U test
  p_value <- wilcox.test(mean ~ is_in_go, data = test_data)$p.value
  
  # Return the GO term and p-value
  data.frame(GO = go, p_value = p_value)
}) %>%
  bind_rows()

# Apply FDR correction
mw_gill_origin <- mw_gill_origin %>%
  mutate(FDR = p.adjust(p_value, method = "fdr"))

# No sig GO terms after FDR correction
filter(mw_gill_origin, FDR < 0.05)

```


```{r}

#gill transplant effect

# Expand the GO terms into a long format for processing
go_long <- go_gill_df %>%
  tidyr::separate_rows(GO, sep = ";")


# Join the logFC data with the GO terms
gill_transplant_logFC_test <- average_lfg_gill_transplant_filtered %>%
  inner_join(go_long, by = "gene_id")

# Get a list of unique GO terms
unique_go <- unique(gill_transplant_logFC_test$GO)


# Perform Mann-Whitney U tests for each GO term
mw_gill_transplant <- lapply(unique_go, function(go) {
  # Create a binary grouping factor: TRUE if gene is associated with the current GO
  test_data <- gill_transplant_logFC_test %>%
    mutate(is_in_go = GO == go)
  
  # Perform the Mann-Whitney U test
  p_value <- wilcox.test(mean ~ is_in_go, data = test_data)$p.value
  
  # Return the GO term and p-value
  data.frame(GO = go, p_value = p_value)
}) %>%
  bind_rows()

# Apply FDR correction
mw_gill_transplant <- mw_gill_transplant %>%
  mutate(FDR = p.adjust(p_value, method = "fdr"))

# No sig GO terms after FDR correction
filter(mw_gill_transplant, FDR < 0.05)

```